In [2]:
import numpy as np

-------------------------Creación y Indexación------------------------------

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [33]:
array_1d = np.random.randint(10,100,(5,5))

print(array_1d)

array_1d[:, 0]


[[99 84 14 57 40]
 [42 15 85 68 12]
 [86 82 32 71 25]
 [95 24 62 80 78]
 [14 80 49 84 14]]


array([99, 42, 86, 95, 14])

In [34]:
print(array_1d[:,0::5])

[[99]
 [42]
 [86]
 [95]
 [14]]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [25]:
array_1d_2 = np.random.randint(1,21,(5,6))

print(array_1d_2)

[[ 9 11  2  4 15  4]
 [15 15 11 12 11 11]
 [12  8  8  8 12 15]
 [11 20  1  1 14  3]
 [ 6  8  2 16  6 20]]


In [30]:
array_1d_2[:,1::2]

array([[11,  4,  4],
       [15, 12, 11],
       [ 8,  8, 15],
       [20,  1,  3],
       [ 8, 16, 20]])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [47]:
array_2d = np.round(np.random.uniform(0, 100, (4,6)),2)

print(array_2d)

[[17.27 80.49 65.09 82.41 22.42 90.97]
 [ 1.51  2.35  6.4  89.16 71.79 57.3 ]
 [ 8.51  5.95 48.61  5.47 23.09 56.32]
 [59.35  8.57 50.19 45.29  8.33 89.86]]


In [48]:
array_2d[-1,:]

array([59.35,  8.57, 50.19, 45.29,  8.33, 89.86])

BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

-------------------------Reshape y Transpose------------------------------


1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [57]:
array_3d = np.random.randint(1,101,(2,3,4))


In [63]:
array_2d = array_3d.reshape(6,4)

print(array_2d)

[[42 47  2 32]
 [56 90 51 12]
 [35 20 83 19]
 [11 47 88 84]
 [76 46 56  4]
 [28 61 72 12]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [65]:
array_3d_2 = np.random.randint(1,61,(3,4,5))

array_3d_2

array([[[15, 13, 13, 38,  8],
        [42, 17,  5, 60,  3],
        [53, 44, 26, 58, 42],
        [44, 37, 12, 31, 56]],

       [[26, 34, 58, 44,  2],
        [ 5,  7, 58, 43,  3],
        [ 2, 35, 45, 31, 11],
        [43, 41, 51, 10, 25]],

       [[33, 19, 47, 56, 31],
        [44, 26, 43, 19, 57],
        [40, 35, 13, 55, 26],
        [21,  2, 59, 25, 53]]])

In [67]:
array_2d_2 = array_3d_2.reshape(10,6)

print(array_2d_2)

[[15 13 13 38  8 42]
 [17  5 60  3 53 44]
 [26 58 42 44 37 12]
 [31 56 26 34 58 44]
 [ 2  5  7 58 43  3]
 [ 2 35 45 31 11 43]
 [41 51 10 25 33 19]
 [47 56 31 44 26 43]
 [19 57 40 35 13 55]
 [26 21  2 59 25 53]]


3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

--------------Preguntas teóricas-------------------------

5. ¿Qué diferencia existe entre el reshape y el transpose?

reshape: Cambia la forma del array sin alterar el orden de los elementos. Permite cambiar el número de dimensiones del array.
transpose: Permuta los ejes del array, cambiando la disposición de los datos a lo largo de las dimensiones.

6. ¿Y entre el transpose y el swapaxes?

transpose: Permite permutar los ejes en cualquier orden, especificando el orden deseado de los ejes.
swapaxes: Intercambia dos ejes específicos del array. Es útil cuando solo se necesitan intercambiar dos dimensiones específicas.

----------------------Funciones Aritméticas y Estadísticas-----------------------------

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".