## Ejercicios Pair Programming Pandas

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

**La serie es una estructura unidimensional y solo puede contener una tipología de datos única, y un dataframe tiene mayor dimensión y puede contener más tipos de datos.**

2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

- Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [1]:
#Importo librerías para trabajar.
import numpy as np
import pandas as pd

In [2]:
#Creo un array unidimensional con números aleatorios.
valores = np.random.randint(0, 8, 7)

#Convierto el array a lista.
lista_valores = list(valores)
print(lista_valores)

#Creo la segunda lista.
indices =  ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']
print(indices)

[1, 3, 3, 1, 0, 2, 4]
['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']


- A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [3]:
serie = pd.Series(valores, index=indices)
serie

lunes        1
martes       3
miercoles    3
jueves       1
viernes      0
sabado       2
domingo      4
dtype: int64

- A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

In [4]:
diccionario = {}
for indice, valor in zip(indices, valores):
    diccionario[indice]= valor

print(diccionario)

{'lunes': 1, 'martes': 3, 'miercoles': 3, 'jueves': 1, 'viernes': 0, 'sabado': 2, 'domingo': 4}


- Crea una Serie con el diccionario creado en el punto anterior.

    - ¿Qué forma tiene esta última Serie?

    - ¿Qué tipo de datos tiene?

    -  ¿Qué tamaño tiene?

    - ¿Cuáles son los índices de la Serie?

    - ¿Y los values?

    - Extrae el valor para el índice "lunes"

    - Extrae el valor para el índice "lunes", "martes" y "miércoles".

    - Extrae el valor para el índice "lunes" y "domingo".

In [5]:
serie = pd.Series(diccionario)
print(serie)

print('_____________________________________________')
#muestro la forma, en este caso unidimensional.
print(serie.shape)

print('_____________________________________________')
#muestro el tipo de datos
print(serie.dtype)

print('_____________________________________________')
#muestro el tamaño
print(serie.size)

print('_____________________________________________')
#muestro el índice
print(serie.index)

print('_____________________________________________')
#muestro los valores
print(serie.values)

print('_____________________________________________')
#busco el valor del índice lunes.
print(serie['lunes'])

print('_____________________________________________')
#busco el valor del índice lunes, martes, miércoles.
print(serie[['lunes', 'martes', 'miercoles']])

print('_____________________________________________')
#busco el valor del índice lunes y domingo.
print(serie[['lunes', 'domingo']])
print('_____________________________________________')
print(serie[[0,6]])

lunes        1
martes       3
miercoles    3
jueves       1
viernes      0
sabado       2
domingo      4
dtype: int64
_____________________________________________
(7,)
_____________________________________________
int64
_____________________________________________
7
_____________________________________________
Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')
_____________________________________________
[1 3 3 1 0 2 4]
_____________________________________________
1
_____________________________________________
lunes        1
martes       3
miercoles    3
dtype: int64
_____________________________________________
lunes      1
domingo    4
dtype: int64
_____________________________________________
lunes      1
domingo    4
dtype: int64


/var/folders/cn/ktnmjcx51q78z4lts32htjr00000gn/T/ipykernel_32651/1817468304.py:36: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(serie[[0,6]])


3. Es el turno de los DataFrames

- Crea un array de dos dimensiones con 4 filas y 3 columnas.

- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

- Descarga el archivo "medallas" y carga el DataFrame.

In [6]:
#Creo el array vacío de las dimensiones que pide el enunciado.
array2D = np.empty((4,3))
print(array2D)

print('_____________________________________________')
#Lo convierto a DataFrame
df_paises = pd.DataFrame(array2D, columns=['España', 'Francia', 'Italia'])
print(df_paises)

print('_____________________________________________')
#Leo el csv de medallas
df_medallas = pd.read_csv('medallas.csv', index_col=0)
print(df_medallas)



[[-2.68156159e+154 -1.73059829e-077  2.96439388e-323]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 2.57726435e-312  2.32035295e+077  8.38737051e-309]]
_____________________________________________
          España       Francia         Italia
0 -2.681562e+154 -1.730598e-77  2.964394e-323
1   0.000000e+00  0.000000e+00   0.000000e+00
2   0.000000e+00  0.000000e+00   0.000000e+00
3  2.577264e-312  2.320353e+77  8.387371e-309
_____________________________________________
               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235


- Usando el loc extrae todas las columnas de la fila de Tailandia.

- Usando el loc extrae todas las columnas de China e Irán.

- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [7]:
#Busco la fila País que cumpla con la condición Tailandia.
tailandia = df_medallas.loc[df_medallas.País == 'Tailandia']
print(tailandia)

print('_____________________________________________')

#Busco la fila País que cumpla con la condición de China o Irán.
china_iran = df_medallas.loc[(df_medallas.País == 'China') | (df_medallas.País == 'Irán')]
print(china_iran)

#Busco la fila País que cumpla con la condición de China o Irán, y busco las columnas de Oro, Plata y Bronce.
print('_____________________________________________')
medallas_china_iran = df_medallas.loc[(df_medallas.País == 'China') | (df_medallas.País == 'Irán'), ['Oro', 'Plata', 'Bronce']]
medallas_china_iran


        País  Oro  Plata  Bronce
7  Tailandia  132    175     278
_____________________________________________
    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197
_____________________________________________


Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

- Usando el iloc extrae la información de la India. Devolved todas las columnas.

- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

- Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [8]:
#Busco todas las columnas de la India.
india = df_medallas.iloc[5]
print(india)

print('_____________________________________________')

#Busco todas las columnas de los paises en posición impar.
impares = df_medallas.iloc[1::2]
print(impares)

#Busco todas las medallas de los paises en posición impar.
print('_____________________________________________')
medallas_impares = df_medallas.iloc[1::2, 1:4]
print(medallas_impares)

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object
_____________________________________________
               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235
_____________________________________________
     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235


- Contesta a las siguientes preguntas:

    - ¿Qué país consiguió más de 200 medallas de oro?

    - ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

    - ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [9]:
#Busco los Paises con más de 200 medallas de oro, filtrando por esa condición.
medallas_oro = df_medallas.loc[(df_medallas['Oro']> 200), ['País', 'Oro']]
medallas_oro

País   Oro
1          China  1473
2          Japón  1032
3  Corea del Sur   745

In [10]:
#Paises con más de 200 medallas de oro y más de 1000 de plata, filtrando por esas dos condiciones.
medallas_oro_plata = df_medallas.loc[(df_medallas.Oro > 200) & (df_medallas.Plata > 1000), ['País', 'Oro', 'Plata']]
medallas_oro_plata

País   Oro  Plata
2  Japón  1032   1037

In [11]:
#Busco los paises con más de 200 medallas de oro o más de 700 de bronce, filtrando por esas dos condiciones.
medallas_oro_bronce = df_medallas.loc[(df_medallas.Oro > 200) | (df_medallas.Bronce > 700), ['País', 'Oro', 'Bronce']]
medallas_oro_bronce

País   Oro  Bronce
1          China  1473     720
2          Japón  1032     985
3  Corea del Sur   745     827

- Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [12]:
# Solo podemos usar el '.Columna' cuando la columna tiene apenas un nombre
df_medallas['Total'] = df_medallas.Oro + df_medallas.Plata + df_medallas.Bronce
df_medallas

País   Oro  Plata  Bronce  Total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446